[package]
name = "gcraft-studios/roblox-template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.5.3"
Fusion = "elttob/fusion@0.2.0"
Signal = "sleitnick/signal@2.0.0"
TableUtil = "sleitnick/table-util@1.1.5"
Janitor = "howmanysmall/janitor@1.15.6"
ZonePlus = "legendoj1/zoneplus@3.2.2"

[server-dependencies]
ProfileService = "firebird702/profileservice@1.1.0"
